### ISSUE TITLE
Why was this a rewrite instead of a plugin?

### ISSUE THREAD

**Issue by faddat** [Radiergummi/Node-Penny-Auctions#1]
So yeah, I guess that's my first question, as someone else trying to extend nodebb, I'd like to know why you chose to rewrite.  Also, you can reach me easily at faddat@gmail.com (hangouts please)

**Comment by Radiergummi** [comment]
Because NodeBB is, in its heart, all based around categories, topics and posts, all things of no use for this project. I decided to go for items and auctions.  
I'll make sure to write you tomorrow (tonight in your TZ ;) )

**Comment by faddat** [comment]
Okay, so I guess-- next question is this:

What parts of NodeBB did you keep?  Which were jettisoned?

**Comment by Radiergummi** [comment]
I only used some parts of the NodeBB code, mostly the socket.io-stuff, as I'm fairly new to that, and the route/controller/middleware loading components. They work great and allow to add new routes really fast. I first started off with Handlebars as the template engine but I didn't like the way they force you to use layout templates, so I got back to [templates.js](https://github.com/psychobunny/templates.js) and implemented my own `<!-- IMPORT -->` routine. I opted to use [Mongoose](https://github.com/Automattic/mongoose) as the database connector, as I like the model binding, though I'm thinking of Redis as a secondary store for auctions and other rapidly changing data, it should be faster after all.  
That's pretty much it, though you'll find the code to be familiar to work with, I think.

**Comment by faddat** [comment]
Oh-- likely I will not.  I'm the interface arm of a group of programmers, but not _much_ of a programmer myself.  I talk the talk pretty well, but well..... I'm slowly learning to walk the walk anyway.  I do know that our crew is really interested in what you're doing, because we're trying to make it incredibly easy for people to accept bitcoin / *coin directly into their wallets without a third party intermediary.  If you'd like though, I can write you a damn fine Dockerfile for both ARM and x86 :).
