### ISSUE TITLE
Web server not starting

### ISSUE THREAD

**Issue by seftera** [Radiergummi/Node-Penny-Auctions#2]
Hi, 
I am trying to use this project as startup for an improved one but one issue I am facing is bin/www script is not starting the webserver. 

10.14.2017 @ 11:14:16:795 - info: Golden Deals v0.0.1, Copyright (C) 2016 Golden Deals GmbH
10.14.2017 @ 11:14:16:807 - info: Developed by Moritz Friedrich (MoritzFriedrich.com).
10.14.2017 @ 11:14:16:809 - info: This program comes with ABSOLUTELY NO WARRANTY.
10.14.2017 @ 11:14:16:809 - info: It is free software, and you are welcome to redistribute it under certain conditions.
10.14.2017 @ 11:14:16:810 - info:
10.14.2017 @ 11:14:16:811 - info: [cluster] Started app with PID 17444

I have done some code changes to get around some issues but it stucks here and does not fork the worker. I was wondering if this was a work in progress part and if not to get it to start node webserver what else I need to do? 

Thanks

**Comment by Radiergummi** [comment]
Hey @seftera, to be honest, I started this project together with some other developers two years ago, only to realize they left off, so I stopped working on this entirely. The current status is a working webserver (at least it has at the time, might depend on old node versions), plus several routes and socket.io integration, not much more.  

If you want to continue, I'd suggest starting fresh without all the overhead and legacy code of this project.  Should you need a hand doing this, point me to your repository and I'll try to help as good as I can.
